### ISSUE TITLE
Avoid `verbosity` symbol in static library. 

### ISSUE THREAD

**Issue by wrtobin** [LLNL/libyogrt#12]
Having `verbosity` as an symbol in the static library can cause conflicts with other libraries doing the same:

``` 
<omitted>/libmili.a(mili.o): In function 'verbosity':
mili.c:(.text+0x5590): multiple definition of 'verbosity'
<omitted>/libyogrt.a(libyogrt_la-yogrt.o):(.bss+0x84): first defined here
/usr/bin/ld: Warning: size of symbol 'verbosity' changed from 4 in <omitted>/libyogrt.a(libyogrt_la-yogrt.o) to 32 in <omitted>/libmili.a(mili.o)
```

prefixing e.g. `yogrt_` should be sufficient to avoid this.

 I've submitted an issue to the other library for the same thing.

**Comment by morrone** [comment]
Absolutely. Fixed in the 1.30 release.
