### ISSUE TITLE
build with LSF support via spack

### ISSUE THREAD

**Issue by gonsie** [LLNL/libyogrt#8]
Hi,

I'm trying to get spack to build libyogrt with LSF support, but it's not clear to me how to explicitly turn on LSF support in the build system. Is that possible, or is LSF automatically detected at configure time?

I have started a PR spack/spack#10884 to add the latest versions of libyogrt. I would like to get the LSF option in there as well. Relatedly, which version(s) of libyogrt have support for LSF?

Thank you!

**Comment by morrone** [comment]
The configure option "--with-lsf=yes" should make it autodetect the LSF parts and fail with an error if it isn't found.  By default it tries to build LSF support and only prints a warning about not building LSF support.

I wouldn't use recommend anything before libyogrt 1.23 with LSF.

**Comment by gonsie** [comment]
My PR was merged. I ended up defaulting to libyogrt's build system for detecting the system-installed scheduler. Since slurm is in spack, I added a way for the user to select and build with a slurm provided by spack itself. This can be done in the future for moab/lsf/other schedulers.
